/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.xlido;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import com.crio.xlido.Repository.EventRepository;
import com.crio.xlido.Repository.IEventRepository;
import com.crio.xlido.Repository.IQuestionRepository;
import com.crio.xlido.Repository.IReplyRepository;
import com.crio.xlido.Repository.IUserRepository;
import com.crio.xlido.Repository.QuestionRepository;
import com.crio.xlido.Repository.ReplyRepository;
import com.crio.xlido.Repository.UserRepository;
import com.crio.xlido.entities.Event;
import com.crio.xlido.entities.User;
import com.crio.xlido.service.EventService;
import com.crio.xlido.service.IEventService;
import com.crio.xlido.service.IQuestionService;
import com.crio.xlido.service.IReplyService;
import com.crio.xlido.service.IUserService;
import com.crio.xlido.service.QuestionService;
import com.crio.xlido.service.ReplyService;
import com.crio.xlido.service.UserService;

public class App {
    IUserRepository repo = new UserRepository();
    IUserService service = new UserService(repo);

    IEventRepository iEventRepository = new EventRepository();
    IEventService eventService = new EventService(iEventRepository, repo);

    IQuestionRepository questionRepo = new QuestionRepository();
    IQuestionService queService = new QuestionService(iEventRepository, repo, questionRepo);

    IReplyRepository replyRepository = new ReplyRepository();
    IReplyService replyService = new ReplyService(replyRepository, questionRepo, repo);

    public static void main(String[] args) {

        // Test your code by ading commands in sample_input/sample_input_one.txt
        // Run run.sh script using "bash run.sh" in your terminal.
        if (args.length == 1){
            List<String> commandLineArgs = new LinkedList<>(Arrays.asList(args));
            String inputFile = commandLineArgs.get(0).split("=")[1];
            try {
                List<String> file_commands = Files.readAllLines(Paths.get(inputFile));
                // Execute the commands
                new App().run(file_commands);
            } catch (IOException e) {
                e.printStackTrace();
            }
            return;
        }        

        // OR
        // Test your code by adding commands in this list
        List<String> inplace_commands = new LinkedList<>(){
            {
            }
        };

        new App().run(inplace_commands);
 
    }
    public void run(List<String> commands){



        Iterator<String> it = commands.iterator();
        while(it.hasNext()){
            String line = it.next();
                if(line == null){
                    break;
                }
                List<String> tokens = Arrays.asList(line.split(","));

                try {
                    //Execute Services
                    switch(tokens.get(0)){
                        case "CREATE_USER":
                           
                            User user = service.addUser(tokens.get(1), tokens.get(2));
                            System.out.println("User ID: " + user.getId());
                        break;
                        case "CREATE_EVENT":
                            Event event = eventService.addEvent(tokens.get(1), Long.parseLong(tokens.get(2)));
                            System.out.println("Event ID: " + event.getId());
                        break;
                        case "DELETE_EVENT":
                            eventService.deleteEvent(Long.parseLong(tokens.get(1)), Long.parseLong(tokens.get(2)));
                        break;
                        case "ADD_QUESTION":
                            queService.addQuestion(tokens.get(1), Long.parseLong(tokens.get(2)), Long.parseLong(tokens.get(3)));
                        break;
                        case "DELETE_QUESTION":
                            queService.deleteQuestion(Long.parseLong(tokens.get(1)), Long.parseLong(tokens.get(2)));
                        break;
                        case "UPVOTE_QUESTION":
                            queService.upvoteQuestion(Long.parseLong(tokens.get(1)), Long.parseLong(tokens.get(2)));
                        break;
                        case "REPLY_QUESTION":
                            replyService.addReply(tokens.get(1), Long.parseLong(tokens.get(2)), Long.parseLong(tokens.get(3)));
                        break;
                        case "LIST_QUESTIONS":
                            replyService.ListQuestion(Long.parseLong(tokens.get(1)), tokens.get(2));
                        break;
                        default:
                            throw new RuntimeException("INVALID_COMMAND");
                }
                } catch (Exception e) {
                    System.out.println("ERROR: " + e.getMessage());
                }
        }
    }
}
